# Generated by Django 4.1 on 2022-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Category',
            new_name='GameCategories',
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='games', through='gamerapi.GameCategories', to='gamerapi.category'),
        ),
    ]
